// GeneratedBankColors.swift
// Auto-generated by scripts/generate-bank-colors.sh — do not edit manually.

import Foundation

enum GeneratedBankColors {
    struct Entry {
        let logoId: String
        let primaryColor: String  // hex without #, e.g. "ee0000"
        let maskable: Bool
    }

    static let all: [Entry] = [
        Entry(logoId: "1822direkt", primaryColor: "003854", maskable: true),
        Entry(logoId: "abnamro", primaryColor: "00a296", maskable: true),
        Entry(logoId: "agrar", primaryColor: "0066b3", maskable: true),
        Entry(logoId: "airbus", primaryColor: "00205b", maskable: true),
        Entry(logoId: "akf", primaryColor: "003671", maskable: true),
        Entry(logoId: "aktiv", primaryColor: "1861cd", maskable: true),
        Entry(logoId: "apo", primaryColor: "012169", maskable: true),
        Entry(logoId: "baader", primaryColor: "062949", maskable: true),
        Entry(logoId: "baer", primaryColor: "141e55", maskable: true),
        Entry(logoId: "bag", primaryColor: "01325b", maskable: true),
        Entry(logoId: "bank11", primaryColor: "5a2382", maskable: true),
        Entry(logoId: "bank1saar", primaryColor: "0066b3", maskable: true),
        Entry(logoId: "bauer", primaryColor: "9d3f43", maskable: true),
        Entry(logoId: "bb", primaryColor: "005ca9", maskable: true),
        Entry(logoId: "bfw", primaryColor: "325f87", maskable: true),
        Entry(logoId: "bhf", primaryColor: "cf2014", maskable: true),
        Entry(logoId: "bib", primaryColor: "242753", maskable: true),
        Entry(logoId: "bnp", primaryColor: "016c47", maskable: true),
        Entry(logoId: "btv", primaryColor: "d00017", maskable: true),
        Entry(logoId: "bundes", primaryColor: "0068a5", maskable: true),
        Entry(logoId: "c24", primaryColor: "0949cf", maskable: true),
        Entry(logoId: "calenberger", primaryColor: "0a369c", maskable: true),
        Entry(logoId: "castell", primaryColor: "f10003", maskable: true),
        Entry(logoId: "comdirect", primaryColor: "fff500", maskable: true),
        Entry(logoId: "commerz", primaryColor: "ffd701", maskable: true),
        Entry(logoId: "consors", primaryColor: "00769e", maskable: true),
        Entry(logoId: "cron", primaryColor: "e3000b", maskable: true),
        Entry(logoId: "cvw", primaryColor: "76bc1e", maskable: true),
        Entry(logoId: "deutsche", primaryColor: "1e2a78", maskable: true),
        Entry(logoId: "dkb", primaryColor: "148dea", maskable: true),
        Entry(logoId: "dkm", primaryColor: "435152", maskable: true),
        Entry(logoId: "donnerreuschel", primaryColor: "014b92", maskable: true),
        Entry(logoId: "edeka", primaryColor: "004b69", maskable: true),
        Entry(logoId: "eih", primaryColor: "16326c", maskable: true),
        Entry(logoId: "ellwanger", primaryColor: "efdfba", maskable: true),
        Entry(logoId: "ethik", primaryColor: "f1b902", maskable: true),
        Entry(logoId: "evangelische", primaryColor: "5a2973", maskable: true),
        Entry(logoId: "evenord", primaryColor: "0066b3", maskable: true),
        Entry(logoId: "fbg", primaryColor: "005279", maskable: true),
        Entry(logoId: "flatex", primaryColor: "009fdf", maskable: true),
        Entry(logoId: "flessa", primaryColor: "0069b4", maskable: true),
        Entry(logoId: "fugger", primaryColor: "003663", maskable: true),
        Entry(logoId: "gls", primaryColor: "00d75c", maskable: true),
        Entry(logoId: "grenke", primaryColor: "000000", maskable: true),
        Entry(logoId: "hal", primaryColor: "001f36", maskable: true),
        Entry(logoId: "haus", primaryColor: "727877", maskable: true),
        Entry(logoId: "hoerner", primaryColor: "9c2340", maskable: true),
        Entry(logoId: "hsbc", primaryColor: "db0011", maskable: true),
        Entry(logoId: "ibb", primaryColor: "326eaa", maskable: true),
        Entry(logoId: "ikano", primaryColor: "ed1c24", maskable: true),
        Entry(logoId: "ikb", primaryColor: "0000cd", maskable: true),
        Entry(logoId: "ing", primaryColor: "ff6200", maskable: true),
        Entry(logoId: "is", primaryColor: "00559f", maskable: true),
        Entry(logoId: "jt", primaryColor: "212529", maskable: true),
        Entry(logoId: "kd", primaryColor: "004c72", maskable: true),
        Entry(logoId: "kontist", primaryColor: "2e2e2e", maskable: true),
        Entry(logoId: "lbbw", primaryColor: "123250", maskable: true),
        Entry(logoId: "liga", primaryColor: "003e79", maskable: true),
        Entry(logoId: "martin", primaryColor: "ad9961", maskable: true),
        Entry(logoId: "mayer", primaryColor: "0d9160", maskable: true),
        Entry(logoId: "merkur", primaryColor: "787d81", maskable: true),
        Entry(logoId: "mkb", primaryColor: "042742", maskable: true),
        Entry(logoId: "mlp", primaryColor: "a3825b", maskable: true),
        Entry(logoId: "mufg", primaryColor: "d32c1f", maskable: true),
        Entry(logoId: "n26", primaryColor: "3f9d8c", maskable: true),
        Entry(logoId: "national", primaryColor: "02a242", maskable: true),
        Entry(logoId: "neelmeyer", primaryColor: "0c2340", maskable: true),
        Entry(logoId: "nibc", primaryColor: "e50000", maskable: true),
        Entry(logoId: "nordlb", primaryColor: "182257", maskable: true),
        Entry(logoId: "ober", primaryColor: "c90000", maskable: true),
        Entry(logoId: "olb", primaryColor: "005f3d", maskable: true),
        Entry(logoId: "opel", primaryColor: "243782", maskable: true),
        Entry(logoId: "pax", primaryColor: "ea6200", maskable: true),
        Entry(logoId: "post", primaryColor: "ffcc00", maskable: true),
        Entry(logoId: "psd", primaryColor: "019966", maskable: true),
        Entry(logoId: "quintet", primaryColor: "008e96", maskable: true),
        Entry(logoId: "raiffeisen", primaryColor: "ffed00", maskable: true),
        Entry(logoId: "rautenschlein", primaryColor: "9c6900", maskable: true),
        Entry(logoId: "renault", primaryColor: "000000", maskable: true),
        Entry(logoId: "renten", primaryColor: "009966", maskable: true),
        Entry(logoId: "revolut", primaryColor: "000000", maskable: true),
        Entry(logoId: "rki", primaryColor: "a71921", maskable: true),
        Entry(logoId: "rsb", primaryColor: "b10035", maskable: true),
        Entry(logoId: "saarlb", primaryColor: "efe205", maskable: true),
        Entry(logoId: "saliter", primaryColor: "b6935d", maskable: true),
        Entry(logoId: "santander", primaryColor: "ec0000", maskable: true),
        Entry(logoId: "seeliger", primaryColor: "816949", maskable: true),
        Entry(logoId: "skb", primaryColor: "006657", maskable: true),
        Entry(logoId: "sozial", primaryColor: "ea7600", maskable: true),
        Entry(logoId: "sparda", primaryColor: "005aaa", maskable: true),
        Entry(logoId: "sparkasse", primaryColor: "ee0000", maskable: true),
        Entry(logoId: "sperrer", primaryColor: "2578c1", maskable: true),
        Entry(logoId: "suedtiroler", primaryColor: "e2001a", maskable: true),
        Entry(logoId: "suedwest", primaryColor: "005a99", maskable: true),
        Entry(logoId: "syd", primaryColor: "002c5c", maskable: true),
        Entry(logoId: "targo", primaryColor: "002c57", maskable: true),
        Entry(logoId: "ten31", primaryColor: "08182e", maskable: true),
        Entry(logoId: "tomorrow", primaryColor: "ff8454", maskable: true),
        Entry(logoId: "triodos", primaryColor: "00937b", maskable: true),
        Entry(logoId: "umwelt", primaryColor: "077d66", maskable: true),
        Entry(logoId: "unicredit", primaryColor: "e2001a", maskable: true),
        Entry(logoId: "union", primaryColor: "bf6019", maskable: true),
        Entry(logoId: "vakif", primaryColor: "fdb913", maskable: true),
        Entry(logoId: "vietin", primaryColor: "005993", maskable: true),
        Entry(logoId: "vivid", primaryColor: "7d33f6", maskable: true),
        Entry(logoId: "volk", primaryColor: "0066b3", maskable: true),
        Entry(logoId: "vw", primaryColor: "004666", maskable: true),
        Entry(logoId: "warburg", primaryColor: "e61e1e", maskable: true),
        Entry(logoId: "weberbank", primaryColor: "662046", maskable: true),
        Entry(logoId: "werhahn", primaryColor: "03a3be", maskable: true),
        Entry(logoId: "werther", primaryColor: "1e3d74", maskable: true),
        Entry(logoId: "yapikredi", primaryColor: "004587", maskable: true),
    ]

    private static let byLogoId: [String: Entry] = {
        all.reduce(into: [:]) { dict, entry in
            if dict[entry.logoId] == nil { dict[entry.logoId] = entry }
        }
    }()

    /// Returns the primary color hex string (without #) for a given logo ID, or nil.
    static func primaryColor(forLogoId id: String) -> String? {
        byLogoId[id]?.primaryColor
    }

    /// Returns true if the SVG for this logo ID is maskable (safe for template rendering).
    static func isMaskable(forLogoId id: String) -> Bool {
        byLogoId[id]?.maskable ?? false
    }
}
