#!/usr/bin/env bash
# Scans bank-logos SVGs and generates GeneratedBankColors.swift
# with logo-id → primary color + maskable flag.

set -euo pipefail

LOGOS_DIR="$(cd "$(dirname "$0")/../Sources/simplebanking/Resources/bank-logos" && pwd)"
OUT="$(cd "$(dirname "$0")/../Sources/simplebanking" && pwd)/GeneratedBankColors.swift"

if [[ ! -d "$LOGOS_DIR" ]]; then
    echo "bank-logos dir not found: $LOGOS_DIR" >&2
    exit 1
fi

cat > "$OUT" <<'HEADER'
// GeneratedBankColors.swift
// Auto-generated by scripts/generate-bank-colors.sh — do not edit manually.

import Foundation

enum GeneratedBankColors {
    struct Entry {
        let logoId: String
        let primaryColor: String  // hex without #, e.g. "ee0000"
        let maskable: Bool
    }

    static let all: [Entry] = [
HEADER

SEEN_IDS_FILE="$(mktemp)"
trap 'rm -f "$SEEN_IDS_FILE"' EXIT

find "$LOGOS_DIR" -name "*.svg" | sort | while IFS= read -r svg; do
    # Skip mask variants — use the base SVG only
    [[ "$svg" == *-mask.svg ]] && continue

    logo_id=$(grep -o 'data-logo-id="[^"]*"' "$svg" 2>/dev/null | head -1 | sed 's/data-logo-id="//;s/"//')
    primary=$(grep -o 'data-primary-color="[^"]*"' "$svg" 2>/dev/null | head -1 | sed 's/data-primary-color="//;s/"//')
    maskable=$(grep -o 'data-maskable="[^"]*"' "$svg" 2>/dev/null | head -1 | sed 's/data-maskable="//;s/"//')

    [[ -z "$logo_id" || -z "$primary" ]] && continue

    # Skip duplicate logo-ids (e.g. stellantis.svg reuses opel's logo-id)
    if grep -qxF "$logo_id" "$SEEN_IDS_FILE" 2>/dev/null; then
        continue
    fi
    echo "$logo_id" >> "$SEEN_IDS_FILE"

    # Strip leading # and truncate to 6 hex chars (drop alpha if present)
    primary="${primary#\#}"
    primary="${primary:0:6}"

    # Check if mask variant exists
    base="${svg%.svg}"
    mask_exists="false"
    [[ -f "${base}-mask.svg" ]] && mask_exists="true"

    maskable_bool="false"
    [[ "$maskable" == "true" || "$mask_exists" == "true" ]] && maskable_bool="true"

    echo "        Entry(logoId: \"$logo_id\", primaryColor: \"$primary\", maskable: $maskable_bool),"
done >> "$OUT"

cat >> "$OUT" <<'FOOTER'
    ]

    private static let byLogoId: [String: Entry] = {
        all.reduce(into: [:]) { dict, entry in
            if dict[entry.logoId] == nil { dict[entry.logoId] = entry }
        }
    }()

    /// Returns the primary color hex string (without #) for a given logo ID, or nil.
    static func primaryColor(forLogoId id: String) -> String? {
        byLogoId[id]?.primaryColor
    }

    /// Returns true if the SVG for this logo ID is maskable (safe for template rendering).
    static func isMaskable(forLogoId id: String) -> Bool {
        byLogoId[id]?.maskable ?? false
    }
}
FOOTER

count=$(grep -c 'Entry(logoId:' "$OUT" || true)
echo "Generated $OUT with $count entries."
